# Configuración de Infraestructura
replicaCount: 2

image:
  repository: ghcr.io/saronos/taylinn
  tag: latest
  pullPolicy: Always

# Variables de Aplicación
env:
  modo: "PRE-PRODUCCIÓN (Rama Main)"
  version: "Release Candidate"
  color_fondo: "#fff3e0" # Naranja claro para avisar que es casi Pro

# Recursos un poco más amplios para pruebas de carga
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi