apiVersion: batch/v1
kind: CronJob
metadata:
  name: limpieza-nocturna
spec:
  schedule: "*/1 * * * *"  # Ejecuta cada minuto
  jobTemplate:             # <--- Debe estar indentado dentro de spec
    spec:
      template:
        spec:
          containers:
          - name: limpiador
            image: busybox
            command:
            - /bin/sh
            - -c
            - date; echo "Limpiando logs viejos... Â¡Hecho!"
          restartPolicy: OnFailure
