apiVersion: apps/v1
kind: Deployment
metadata:
  name: taylinn
  labels:
    app: taylinn
spec:
  replicas: 3  # Empezamos con 1 pod
  selector:
    matchLabels:
      app: taylinn
  template:
    metadata:
      labels:
        app: taylinn
    spec:
      containers:
      - name: python-app
        # OJO: Aquí debe poner la dirección de SU imagen (ghcr.io/usuario/...)
        image: ghcr.io/saronos/taylinn:latest 
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        # Health Checks (Vital para DevOps)
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
