apiVersion: apps/v1
kind: Deployment
metadata:
  name: taylinn
  labels:
    app: taylinn
spec:
  replicas: 1  # Empezamos con 1, el HPA lo subirá si hay tráfico
  selector:
    matchLabels:
      app: taylinn
  template:
    metadata:
      labels:
        app: taylinn
    spec:
      containers:
      - name: python-app
        image: ghcr.io/saronos/taylinn:latest 
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: 
          requests:
            cpu: "50m"      # Reserva el 5% de un núcleo
            memory: "64Mi"
          limits: 
            cpu: "200m"     # No deja que pase del 20%
            memory: "256Mi"